name: Build and deploy ASP.Net Core app to Azure Web App - apiperfumes

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 9.0.202
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '9.0.202'

      - name: Restore dependencies
        run: dotnet restore src/MasterNet.WebApi/MasterNet.WebApi.csproj

      - name: Build
        run: dotnet build src/MasterNet.WebApi/MasterNet.WebApi.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish src/MasterNet.WebApi/MasterNet.WebApi.csproj --configuration Release --output ./publish --no-build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'apiperfumes'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_410F92337D4948E298D57670280E0FDF }}
          package: .

