# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# Más acciones de GitHub para Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - apiperfumes

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore ./src/MasterNet.WebApi/MasterNet.WebApi.csproj

      - name: Build project
        run: dotnet build ./src/MasterNet.WebApi/MasterNet.WebApi.csproj --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish ./src/MasterNet.WebApi/MasterNet.WebApi.csproj --configuration Release --output ./publish --no-build

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: webapp

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'apiperfumes'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_410F92337D4948E298D57670280E0FDF }}
          package: .
